name: raster_mgmt

channels:
  - esri
  - conda-forge

dependencies:
  - arcgis
  - black>=21
  - cookiecutter
  - jupyterlab
  - jupyterlab_code_formatter
  - nodejs
  - pandoc
  - pip
  - pytest
  - python=3.9
  - swifter
  - pip:
    - autodocsumm
    - azure-storage-blob
    - build
    - bump2version
    - furo
    - nbsphinx
    - sphinx
    - sphinxcontrib-youtube
    - sphinx-autodoc-typehints
    - sphinx-copybutton
    - twine
